City1
KirillGusev/ingipro2 pull request #11
Opened 2017-07-20 18:01 UTC by KirillGusev

@ixax @mar4uk

2017-07-20 19:29 UTC, ixax requested changes

2017-07-20 19:29 UTC, ixax commented on city1.js
> +    alert(`Температура в Цельсиях: ${json.main.temp}\nПродолжительность дня: ${dayLongInStr}\nСкорость ветра: ${json.wind.speed}`);
Строковые шаблоны умеют перенос строк, не надо вставлять спец. символы

2017-07-20 19:29 UTC, ixax commented on city1.js
> +    function getLongInStr(dayLongInSec) {
Создание ф-ии внутри маложивущего кода — плохо, у тебя при каждом вызове происходит пересоздание ф-ии..
Вынеси в шапку файла, чтобы ф-ия создавалась один раз и не ела память

2017-07-23 20:06 UTC, mar4uk approved these changes

2017-07-23 20:06 UTC, mar4uk commented
👍

2017-07-23 20:06 UTC, closed without merging