City3
KirillGusev/ingipro2 pull request #13
Opened 2017-07-20 18:01 UTC by KirillGusev

@ixax  @mar4uk

2017-07-20 19:34 UTC, ixax requested changes

2017-07-20 19:34 UTC, ixax commented on city3.js
> +    let result = ``;
Создай пустой массив.
В цикле сделай в него push
В момент вызова сделай `arr.join('\n')`
В таком случае тебе не надо в конце каждой строки ставить `\n`

2017-07-20 19:34 UTC, ixax commented on city3.js
> +  Promise.all( arrCities.map( name => fetch(`http://api.openweathermap.org/data/2.5/weather?q=${name}&units=metric&appid=bd5e378503939ddaee76f12ad7a97608`)
С переносами вообще жара, код нечитаем :/

2017-07-23 20:07 UTC, mar4uk approved these changes

2017-07-23 20:07 UTC, mar4uk commented
👍

2017-07-23 20:07 UTC, closed without merging