commit city4
KirillGusev/ingipro2 pull request #14
Opened 2017-07-20 18:02 UTC by KirillGusev

@ixax @mar4uk

2017-07-20 19:36 UTC, ixax requested changes

2017-07-20 19:36 UTC, ixax commented on city4.js
> +    return fetch(`http://api.openweathermap.org/data/2.5/find?lat=${city.lat}&lon=${city.lon}&cnt=${NumberCities + 1}&units=metric&appid=bd5e378503939ddaee76f12ad7a97608`)
Почему бы тут не использовать `await`?

2017-07-23 20:20 UTC, mar4uk requested changes

2017-07-23 20:20 UTC, mar4uk commented on city4.js
> +        tempMax.name = cities[index].name;
значение `cities[index].name` хранится в `name`. Используй `name`, это короче

2017-07-23 20:20 UTC, mar4uk commented on city4.js
> +async function getCitiesTempMax(centralCityName, NumberCities) {
Название функции не отражает, то что она делает.
Функция возвращает просто список городов, не вычисляет максимальную температуру. TempMax в названии - лишнее.

2017-07-23 20:20 UTC, mar4uk commented on city4.js
> +async function findTempMax(centralCityName, NumberCities) {
название переменной в camelCase.
NumberCities -> numberCities

2017-07-24 08:41 UTC, mar4uk approved these changes

2017-07-24 08:41 UTC, mar4uk commented
👍

2017-07-24 08:41 UTC, closed without merging