2 ok
KirillGusev/ingipro2 pull request #4
Opened 2017-07-17 16:06 UTC by KirillGusev

@ixax @mar4uk

2017-07-17 17:29 UTC, ixax requested changes

2017-07-17 17:29 UTC, ixax commented on 2.js
> +function palindrome(str) {
Сложновато как-то
@mar4uk?

2017-07-19 07:58 UTC, mar4uk commented on 2.js
> +function palindrome(str) {
Да, на самом деле можно. И скорее всего в дальнейшей разработке так и будем делать.
Но, если думать о сложности и оптимальности алгоритма, то reverse не самый оптимальный способ.
Оба решения принимаются)

2017-07-19 07:59 UTC, mar4uk approved these changes

2017-07-19 07:59 UTC, mar4uk commented
👍

2017-07-19 07:59 UTC, closed without merging