3 ok
KirillGusev/ingipro2 pull request #5
Opened 2017-07-17 16:15 UTC by KirillGusev

@ixax @mar4uk

2017-07-17 17:38 UTC, ixax requested changes

2017-07-17 17:38 UTC, ixax commented on 3.js
> +    console.log(buff);
зачем это тут?

2017-07-17 17:38 UTC, ixax commented on 3.js
> +function chunkArrayInGroups(arr, size) {
Продолжай проверять крайние значения.
На size <= 0 у тебя программа зайдёт в цикл и никогда больше оттуда не выползет

2017-07-19 07:38 UTC, mar4uk commented on 3.js
> +  const remnant = arr.length % size;
если size = 0 будет NaN

2017-07-19 17:31 UTC, closed without merging