4 ok
KirillGusev/ingipro2 pull request #6
Opened 2017-07-17 16:15 UTC by KirillGusev

@ixax @mar4uk

2017-07-17 17:35 UTC, ixax requested changes

2017-07-17 17:35 UTC, ixax commented on 4.js
> +if (!(typeof arr[0] === "number") || !(typeof arr[1] === "number")) {
Проверить что передан правильный массив можно как-то так: `arr.every(item => typeof item === 'number' && item &  NaN)`
По первому элементу понять это сложно.

2017-07-17 17:35 UTC, ixax commented on 4.js
> +if (arr[0] > arr[1]) {
Что ты тут делаешь?

2017-07-17 17:35 UTC, ixax commented on 4.js
> +function sumAll(arr) {
у тебя весь код влево сдвинут

2017-07-17 17:44 UTC, KirillGusev commented on 4.js
> +if (arr[0] > arr[1]) {
@ixax  одно из свойств функции, чтобы она она суммировала от одного элемента до другого и так как я делаю это в цикле, я определяю какое из них меньше и начинаю цикл с него

2017-07-19 07:55 UTC, mar4uk approved these changes

2017-07-19 07:55 UTC, mar4uk commented
👍

2017-07-19 07:55 UTC, closed without merging